version: '3'

services: 
    db:
        build: ./Docker/mysql-microservice
        environment: 
             MYSQL_DATABASE: tp_igl
             MYSQL_ROOT_PASSWORD: password
             MYSQL_USER: narimane
             MYSQL_PASSWORD: password
             DATABASE_HOST: db
    node:
        build: ./
        environment: 
            DATABASE_HOST: db
            MYSQL_PORT: 3306
            MYSQL_DATABASE: tp_igl
            MYSQL_USER: narimane
            MYSQL_PASSWORD: password
        ports:
            - "3003:3003"
        depends_on: 
            - db
        restart: on-failure 